name: Deploy to Cloud Run (Dev)

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

concurrency:
  group: cloud-run-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
        env:
          CI: true

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
      REGION: asia-northeast1
      SERVICE_NAME: db-service-dev
      IMAGE_SHA: gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/db-service-dev:${{ github.sha }}
      IMAGE_LATEST: gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/db-service-dev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_DEV }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker --quiet

      # 依存導入/ビルドは Dockerfile の中で実施（ここで yarn build はしない）
      - name: Build Docker image
        run: |
          docker build -t "${IMAGE_SHA}" .
          docker tag "${IMAGE_SHA}" "${IMAGE_LATEST}"

      - name: Push Docker image
        run: |
          docker push "${IMAGE_SHA}"
          docker push "${IMAGE_LATEST}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${SERVICE_NAME}" \
            --image "${IMAGE_SHA}" \
            --platform managed \
            --region "${REGION}" \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 5
          # 環境変数/Secret を設定する場合は以下を追記:
          #  --set-env-vars KEY=VALUE,KEY2=VALUE2 \
          #  --set-secrets NOTIFICATION_API_KEY=notification-api-key:latest
